# Generated by Django 4.0.3 on 2023-03-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_from', models.CharField(choices=[('8:00', '8:00'), ('8:45', '8:45'), ('9:30', '9:30'), ('10:15', '10:15'), ('11:00', '11:00'), ('11:45', '11:45'), ('12:30', '12:30'), ('13:15', '13:15'), ('14:00', '14:00'), ('14:45', '14:45'), ('15:30', '15:30'), ('16:15', '16:15'), ('17:00', '17:00'), ('17:30', '17:30')], max_length=100)),
                ('time_to', models.CharField(choices=[('8:00', '8:00'), ('8:45', '8:45'), ('9:30', '9:30'), ('10:15', '10:15'), ('11:00', '11:00'), ('11:45', '11:45'), ('12:30', '12:30'), ('13:15', '13:15'), ('14:00', '14:00'), ('14:45', '14:45'), ('15:30', '15:30'), ('16:15', '16:15'), ('17:00', '17:00'), ('17:30', '17:30')], max_length=100)),
                ('test', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
