# Generated by Django 4.0.3 on 2023-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(error_messages={'unique': 'Service with name already exists'}, max_length=100, unique=True),
        ),
    ]
