# Generated by Django 4.0.3 on 2023-03-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator_app', '0001_initial'),
        ('worker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker'),
        ),
    ]
