# Generated by Django 4.2.1 on 2023-05-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='worker_assignment',
        ),
        migrations.CreateModel(
            name='WorkTimeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('worker_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workdayassignment')),
                ('worktime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.worktime')),
            ],
        ),
    ]
