# Generated by Django 4.0.3 on 2023-04-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
