# Generated by Django 4.0.3 on 2023-04-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_remove_order_worker_and_date'),
        ('administrator_app', '0002_workday_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkDayAssignment',
        ),
    ]
