# Generated by Django 4.0.3 on 2023-03-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_remove_order_date_remove_order_worker_and_more'),
        ('worker_app', '0001_initial'),
        ('administrator_app', '0003_workday_workdayassignment_remove_workschedule_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
        migrations.AddField(
            model_name='workdayassignment',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workday'),
        ),
        migrations.AddField(
            model_name='workdayassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker'),
        ),
    ]
