# Generated by Django 4.0.3 on 2023-04-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0001_initial'),
        ('administrator_app', '0003_delete_workdayassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workday')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker')),
            ],
        ),
    ]
