# Generated by Django 4.0.3 on 2023-01-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0003_alter_service_service_name_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
