# Generated by Django 4.0.3 on 2023-04-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0004_delete_workschedule_workdayassignment_workday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
    ]
