# Generated by Django 4.0.3 on 2023-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0004_workdayassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdayassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
