# Generated by Django 4.0.3 on 2023-01-31 05:39

import administrator_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker_app', '0001_initial'),
        ('administrator_app', '0004_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('8:00', administrator_app.models.WorkTime('8:00')), ('8:45', administrator_app.models.WorkTime('8:45')), ('9:30', administrator_app.models.WorkTime('9:30')), ('10:15', administrator_app.models.WorkTime('10:15')), ('11:00', administrator_app.models.WorkTime('11:00')), ('11:45', administrator_app.models.WorkTime('11:45')), ('12:30', administrator_app.models.WorkTime('12:30')), ('13:15', administrator_app.models.WorkTime('13:15')), ('14:00', administrator_app.models.WorkTime('14:00')), ('14:45', administrator_app.models.WorkTime('14:45')), ('15:30', administrator_app.models.WorkTime('15:30')), ('16:15', administrator_app.models.WorkTime('16:15')), ('17:00', administrator_app.models.WorkTime('17:00')), ('17:30', administrator_app.models.WorkTime('17:30'))], default='8:00', max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker')),
            ],
        ),
    ]
