# Generated by Django 4.0.3 on 2023-04-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0005_alter_workdayassignment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
