# Generated by Django 4.0.3 on 2023-04-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0006_alter_workday_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='active',
        ),
        migrations.RemoveField(
            model_name='workdayassignment',
            name='is_active',
        ),
    ]
