# Generated by Django 4.0.3 on 2023-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0006_alter_workschedule_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='time',
            new_name='time_from',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='time_to',
            field=models.CharField(choices=[('8:00', '8:00'), ('8:45', '8:45'), ('9:30', '9:30'), ('10:15', '10:15'), ('11:00', '11:00'), ('11:45', '11:45'), ('12:30', '12:30'), ('13:15', '13:15'), ('14:00', '14:00'), ('14:45', '14:45'), ('15:30', '15:30'), ('16:15', '16:15'), ('17:00', '17:00'), ('17:30', '17:30')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
