# Generated by Django 4.0.3 on 2023-05-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0008_alter_workdayassignment_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdayassignment',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workday'),
        ),
    ]
