# Generated by Django 4.0.3 on 2023-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0009_alter_workschedule_time_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='test',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
