# Generated by Django 4.0.3 on 2023-05-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0009_alter_workdayassignment_workday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
