# Generated by Django 4.0.3 on 2023-03-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0010_workschedule_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='test',
        ),
    ]
