# Generated by Django 4.0.3 on 2023-03-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0013_workschedule_time_range'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRange',
        ),
    ]
