# Generated by Django 4.0.3 on 2023-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0014_delete_timerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='time_range',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='test',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
