# Generated by Django 4.0.3 on 2023-03-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0015_remove_workschedule_time_range_workschedule_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='test',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
