# Generated by Django 4.0.3 on 2023-03-22 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotRegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Must be unique'}, max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(choices=[('8:00', '8:00'), ('8:45', '8:45'), ('9:30', '9:30'), ('10:15', '10:15'), ('11:00', '11:00'), ('11:45', '11:45'), ('12:30', '12:30'), ('13:15', '13:15'), ('14:00', '14:00'), ('14:45', '14:45'), ('15:30', '15:30'), ('16:15', '16:15'), ('17:00', '17:00'), ('17:30', '17:30')], verbose_name='Time of service')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workschedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
