# Generated by Django 4.0.3 on 2023-04-27 17:02

import client_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotRegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Must be unique'}, max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('9:00', client_app.models.Time('9:00')), ('9:45', client_app.models.Time('9:45')), ('10:30', client_app.models.Time('10:30')), ('11:15', client_app.models.Time('11:15')), ('12:00', client_app.models.Time('12:00')), ('12:45', client_app.models.Time('12:45')), ('13:30', client_app.models.Time('13:30')), ('14:15', client_app.models.Time('14:15')), ('15:00', client_app.models.Time('15:00')), ('15:45', client_app.models.Time('15:45')), ('16:30', client_app.models.Time('16:30'))], max_length=100, verbose_name='Time of service')),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker_and_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workdayassignment')),
            ],
        ),
    ]
