# Generated by Django 4.0.3 on 2023-04-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='worker_and_date',
        ),
    ]
