# Generated by Django 4.0.3 on 2023-04-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0005_alter_workdayassignment_is_active'),
        ('client_app', '0002_remove_order_worker_and_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_and_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workdayassignment'),
            preserve_default=False,
        ),
    ]
