# Generated by Django 4.1.3 on 2022-12-03 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker_app', '0001_initial'),
        ('client_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator_app.service')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='worker_app.worker')),
            ],
        ),
    ]
