# Generated by Django 4.0.3 on 2023-03-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator_app', '0003_workday_workdayassignment_remove_workschedule_worker'),
        ('client_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='worker',
        ),
        migrations.AddField(
            model_name='order',
            name='worker_and_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator_app.workdayassignment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=100, verbose_name='Time of service'),
        ),
    ]
