# Generated by Django 4.1.3 on 2022-12-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='service',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='time',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='worker',
        ),
    ]
