# Generated by Django 4.0.3 on 2023-04-24 15:15

import client_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_order_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(choices=[('9:00', client_app.models.Time('9:00')), ('9:45', client_app.models.Time('9:45')), ('10:30', client_app.models.Time('10:30')), ('11:15', client_app.models.Time('11:15')), ('12:00', client_app.models.Time('12:00')), ('12:45', client_app.models.Time('12:45')), ('13:30', client_app.models.Time('13:30')), ('14:15', client_app.models.Time('14:15')), ('15:00', client_app.models.Time('15:00')), ('15:45', client_app.models.Time('15:45'))], max_length=100, verbose_name='Time of service'),
        ),
    ]
