# Generated by Django 4.0.3 on 2023-05-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_alter_feedback_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client_app.order'),
        ),
    ]
