# Generated by Django 4.0.3 on 2023-01-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_alter_not_registered_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Not_registered_user',
            new_name='NotRegisteredUser',
        ),
    ]
