# Generated by Django 4.0.3 on 2023-05-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_feedback_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotRegisteredUser',
        ),
        migrations.AddField(
            model_name='order',
            name='has_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
