# Generated by Django 4.0.3 on 2023-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_delete_notregistereduser_order_has_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
